### ISSUE TITLE
Cannot load materials example

### ISSUE THREAD

**Issue by hadronized** [3MFConsortium/3mf-samples#1]
When I try to open them, I get these errors:

> could not parse file: 80004005
> error #1035: Could not read ZIP file

I read them with the `lib3mf_reader_readfromfileutf8` function. Any idea?

**Comment by hadronized** [comment]
Ok, it works with the dodeca_chain_loop, but not pyramid, for instance.

**Comment by mvelayati** [comment]
I want to create a multi <object> .3mf shape, I used the "Cube" code and created some kind of a loop to create multiple mesh objects but my code is not outputting anything. Since there should be one <object> for different parts, do I have to create multiple <object> tags? I don't see the command for it.

**Comment by pencerw** [comment]
@phaazon we just rebuilt our materials examples directory; can you check the files there and reconfirm?

**Comment by hadronized** [comment]
Hello,

I worked on that in a company I left more than a year ago. Sorry. :/
